### ISSUE TITLE
Blocked a frame with origin if using subdomain

### ISSUE THREAD

**Issue by fpoobus** [EmbeddedEnterprises/ng6-golden-layout#6] opened 2018-10-05 07:42 UTC
Hi

I am having some issues when running under a subdomain. Everything seems to work fine under localhost and somehow everything works fine when running incognito window. 

ERROR DOMException: Blocked a frame with origin "https://app.visualnovelist.net" from accessing a cross-origin frame.

Seems to be caused by this line:
GoldenlayoutComponent:
anyWin.__apprefs.push(this.appref);

I also changed my apache settings and moved from subdomain to main domain which seemned to work. 

Am I doing something wrong?

Thanks

**Comment by martin31821** [comment] 2018-10-05 12:30
I think this is a server issue, could you dump your headers and paste them here?

**Comment by fpoobus** [comment] 2018-10-05 13:28
I removed target="_blank" from my href that linked to the angular app and now it works for some reason. (It used to work with direct linking before ).

I compared the headers and saw no difference between the direct linking and href request.

**Comment by martin31821** [comment] 2018-10-05 13:34
The code that decides whether to create a `parent` or a `child` window context relies on the presence of `window.opener` (or absence, for a parent context). When you are linking with `target=_blank`, `window.opener` is set to the window instance in the parent, which means that the CORS rules from there apply (even if they didn't, the problem is that the `child` contexts rely on the `parent` context being initialized first, wouldn't work anyway)

If you'd like to keep the target, add `rel=noopener` to your `<a>` element. (See: https://developers.google.com/web/tools/lighthouse/audits/noopener)

I'm closing this, as it's not a direct problem with this component, but with the embedding website.

**Closed as completed by martin31821** 2018-10-05 13:34 UTC
Labels: invalid, question
