### ISSUE TITLE
Problem when using the router

### ISSUE THREAD

**Issue by benedetto-kotzaneck** [EmbeddedEnterprises/ng6-golden-layout#15] opened 2019-02-20 08:21 UTC
I try to use the ng6-golden-layout for a specific route in angular. I have the <golden-layout-root> tag inside the template of the component of the route which i am opening.
When opening that route I get the following error:

Init@root! embedded-enterprises-ng6-golden-layout.js:184 
Create@root! embedded-enterprises-ng6-golden-layout.js:189 
Init@root! embedded-enterprises-ng6-golden-layout.js:184 
Create@root! embedded-enterprises-ng6-golden-layout.js:184
Create@root! core.js:15714 ERROR RangeError: Maximum call stack size exceeded
    at embedded-enterprises-ng6-golden-layout.js:199

Can't seem to find the error. I'm trying this because I want to use the golden-layout only for a specific route. I hope someone can help me at this.

**Comment by martin31821** [comment] 2019-02-20 21:22
I'm using the component successfully inside a router outlet, so that must be something specific to your code. Can you share a minimal reproduction of your bug?
It seems to be an endless recursion.

**Comment by benedetto-kotzaneck** [comment] 2019-02-21 06:34
Hi Martin, thanks for the fast reply. I've found the error that was causing the recursion.
I specified the component which should be rendered inside golden-layout in the router.

**Comment by martin31821** [comment] 2019-02-21 07:57
Okay, I'm going to close it then :smile:

**Closed as completed** 2019-02-21 07:57 UTC
Labels: bug

**Comment by Jean-PhilippeGouin** [comment] 2019-03-23 09:37
Hi @martin31821 ,

Do you have a working example of golden layout inside a router ?
