### ISSUE TITLE
how to access glEventhub in angular 

### ISSUE THREAD

**Issue by shobanmr** [EmbeddedEnterprises/ng6-golden-layout#22] opened 2019-06-19 05:05 UTC
I have understood the code in embedded-enterprises-ng6-golden-layout.js 

```
class GoldenLayoutComponent {
     ............
  ngOnInit() {
     this.glService.getState().then((layout) => {
            this._createLayout(layout);
        });
  }

}

```

After the layout is created, In glService we are getting the eventHub, But we need to access these in angular components how to export it

**Comment by martin31821** [comment] 2019-06-19 06:02
Duplicate of #21

**Closed as completed by martin31821** 2019-06-19 06:02 UTC
Labels: duplicate
